name: Build every package in different environments.

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release/**'
  workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:
  build-all:
    name: Build all packages in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # https://github.com/actions/setup-node/releases/tag/v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install the dependencies
        run: npm ci

      - name: Build all packages
        run: npm run all build
