name: Build every package in different environments.

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release/**'
  workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:
  build-on-unix:
    name: Build all packages in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # https://github.com/actions/setup-node/releases/tag/v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install the dependencies
        run: npm ci

      - name: Build all packages
        run: npm run all build

  build-on-windows:
    name: Build all packages in windows-latest
    runs-on: windows-latest
    steps:
      # on C drive there is more free space left to do this job (https://github.com/actions/runner-images/issues/1341#issuecomment-667478747)
      - name: Checkout
        run: |
          mkdir C:/handsontable
          git clone -b $env:GITHUB_REF_NAME https://github.com/handsontable/handsontable C:/handsontable --depth 1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # https://github.com/actions/setup-node/releases/tag/v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install the dependencies
        working-directory: C:/handsontable
        run: npm ci

      - name: Build all packages
        working-directory: C:/handsontable
        run: npm run all build
