name: Publish prerelease in NPM

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [develop, 'release/**']

env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # https://github.com/actions/checkout/releases/tag/v2.5.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # https://github.com/actions/setup-node/releases/tag/v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_AUTOMATION }}
      - run: npm install
      - run: npm run build
      - run: npm run prerelease-to-npm
