name: Publish prerelease in NPM

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches:
      - 'develop'
      - 'release/**'
      - '!release/**-**'

env:
  NODE_VERSION: 16

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # https://github.com/actions/setup-node/releases/tag/v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          cache-dependency-path: package-lock.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_AUTOMATION }}
      - run: npm install
      - run: npm run pre-release
