name: TMP - Test the CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release/**'
  workflow_dispatch:

env:
  NODE_VERSION: 16.x

jobs:
  build-handsontable-umd:
    name: "[BUILD] Handsontable: UMD"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # https://github.com/actions/checkout/releases/tag/v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954 # https://github.com/actions/setup-node/releases/tag/v2.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci --no-audit
      - name: Build
        run: |
          cd handsontable
          npm run build:umd && npm run build:languages
          npm run build:umd.min && npm run build:languages.min
      - run: tar -zcf dist.tar.gz ./handsontable/dist
      - name: Upload the Handsontable UMD build artifact.
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # https://github.com/actions/upload-artifact/releases/tag/v2.2.4
        with:
          name: handsontable-build-umd
          path: |
            dist.tar.gz

  test-handsontable-e2e:
    name: "[TEST] Handsontable: UMD"
    runs-on: ubuntu-latest
    needs: [ build-handsontable-umd ]
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # https://github.com/actions/checkout/releases/tag/v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954 # https://github.com/actions/setup-node/releases/tag/v2.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci --no-audit
      - name: Download the Handsontable build artifact
        uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # https://github.com/actions/download-artifact/releases/tag/v2.0.10
        with:
          name: handsontable-build-umd
          path: ./
      - run: tar -zxf dist.tar.gz ./handsontable/dist && rm dist.tar.gz
      - name: Test
        run: |
          cd handsontable
          npm run test:e2e.dump && npm run test:e2e.puppeteer
