name: Visual tests

on:
  workflow_dispatch:
  push:
  
env:
  NODE_VERSION: 16

jobs:
  build:
    name: Build and make visual test
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # https://github.com/actions/setup-node/releases/tag/v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: run visual tests
        run: node scripts/visual-test.mjs
      - name: upload visual test screenshot
      env:
        ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
        VISWIZ_API_KEY: ${{ secrets.VISWIZ_API_KEY }}
        VISWIZ_PROJECT_ID: ${{ secrets.VISWIZ_PROJECT_ID }}
      run: node scripts/visual-test-upload-screenshot.mjs
